const CONFIG = {
    titleWeb: "Hi! Mèo Tây",
    introTitle: 'Bé nè @_@',
    introDesc: `Chị và bé là hai con người đối lập. Thời điểm hiện tại dù chưa hiểu nhau, nhưng cũng đang tiếp nhận đối phương đúng hong?`,
    btnIntro: '<Hẹ Hẹ>',
    Color: 'White',
    title: 'Mọi khi câu này là bé hay gài chị',
    desc: 'Giờ tới chị hỏi bé nhé! Bé có thương chị hong🥰 ',
    Color: 'Blue',
    btnYes:'Thương nhiều chút <33', 
    btnNo: 'Chắc là hong hả :3',
    question: 'Cũng kệ luôn, Chị thương bé là được <3',
    btnReply: 'Chị |0ve Bé <3',
    reply: 'Vậy bây giờ tụi mình cùng bước tới giai đoạn tiếp theo nhé! <33333333',
    mess: 'Bé đồng ý làm người yêu của chị hong? 🥰. (Không biết tương lại thế nào, nhưng mà chị sẽ cố gắng) 😘😘',
    messDesc: 'Bé có thể không trả lời chị, thời hạn là đến khi chị và bé gặp nhau chính thức thì nhớ trả lời chị nhé!',
    btnAccept: 'Chị đợi bé <3',
    }
